-- Expand back types, door types, and upper-cabinet options on Order

ALTER TYPE "BackType" ADD VALUE 'RECTIFICATION';
ALTER TYPE "BackType" ADD VALUE 'OVERLAID_SOLID';
ALTER TYPE "BackType" ADD VALUE 'DADO_SOLID';

CREATE TYPE "DoorType" AS ENUM ('HANDLE', 'HANDLE_BAR', 'TIP_ON', 'NONE');

ALTER TABLE "Order" ADD COLUMN "shelfCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Order" ADD COLUMN "visibleSideLeft" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "visibleSideRight" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "topRailEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "topRailOverhang" INTEGER NOT NULL DEFAULT 21;
ALTER TABLE "Order" ADD COLUMN "topRailLed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "topRailLedColor" VARCHAR(30);
ALTER TABLE "Order" ADD COLUMN "topRailLedControl" VARCHAR(30);
ALTER TABLE "Order" ADD COLUMN "bottomRailEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "bottomRailLed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "bottomRailLedType" VARCHAR(20);
ALTER TABLE "Order" ADD COLUMN "bottomRailLedColor" VARCHAR(30);
ALTER TABLE "Order" ADD COLUMN "bottomRailLedControl" VARCHAR(30);
ALTER TABLE "Order" ADD COLUMN "doorType" "DoorType" NOT NULL DEFAULT 'HANDLE';
ALTER TABLE "Order" ADD COLUMN "handleId" INTEGER;
ALTER TABLE "Order" ADD COLUMN "handleBarHeight" INTEGER;
ALTER TABLE "Order" ADD COLUMN "hingeOverride" INTEGER;

ALTER TABLE "Order" ADD CONSTRAINT "Order_handleId_fkey"
  FOREIGN KEY ("handleId") REFERENCES "Hardware"("id") ON DELETE SET NULL ON UPDATE CASCADE;
